authentication/urls.py
from django.urls import include, path

from .views import classroom, students, teachers
from . import views
from .views.classroom import *

urlpatterns = [
path('token/' , token_send , name="token_send"),
path('success/' , success , name='success'),
path('verify/<auth_token>' , verify , name="verify"),
path('error/' , error_page , name="error"),
path('change_password/', classroom.change_password, name='change_password'),
path('edit_profile/',classroom.edit_profile, name="edit_profile"),
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.S_dashboard, name='S_dashboard'),
        path('quiz_list', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.T_dashboard, name='T_dashboard'),
        path('quiz_add_category', teachers.QuizAddCategoryView.as_view(), name='quiz_add_category'),
        path('quiz_change_list', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'classroom'), namespace='teachers')),
]

classroomquiz/urls.py
from django.urls import include, path
from django.contrib import admin
from authentication.views import classroom, students, teachers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('authentication.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.username



class Profile(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    auth_token  = models.CharField(max_length=100 )
    is_verified = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text

# student model
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Category, related_name='interested_students')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username
            


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quiz

class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

# teacher model
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)


    def __str__(self):
    	return self.user.username

authentication/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from authentication.forms import EditProfileForm
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from authentication.forms import PasswordChangingForm

class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:T_dashboard')
        else:
            return redirect('students:S_dashboard')
    return render(request, 'home.html')

#account activation using gmail account
def success(request):
    return render(request , 'registration/success.html')


def token_send(request):
    return render(request , 'registration/token_send.html')


def verify(request , auth_token):
    try:
        profile_obj = Profile.objects.filter(auth_token = auth_token).first()
    

        if profile_obj:
            if profile_obj.is_verified:
                messages.success(request, 'Your account is already verified.')
                return redirect('/login')
            profile_obj.is_verified = True
            profile_obj.save()
            messages.success(request, 'Your account has been verified.')
            return redirect('/login')
        else:
            return redirect('/error')
    except Exception as e:
        print(e)
        return redirect('/success')

def error_page(request):
    return  render(request , 'registration/error.html')

def send_mail_after_registration(email , token):
    subject = 'Your accounts need to be verified'
    message = f'Click HERE to verify your account! http://127.0.0.1:8000/verify/{token}'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message , email_from ,recipient_list )

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangingForm(data=request.POST, user= request.user)
		if form.is_valid():
			form.save()
			messages.success(request,('You Have Edited Your Password...'))
			return redirect('home')
	else:
		form = PasswordChangingForm(user= request.user)

	context = {'form': form}
	return render(request, 'registration/change_password.html', context)

def edit_profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance= request.user)
		if form.is_valid():
			form.save()
			messages.success(request,('You Have Edited Your Profile...'))
			return redirect('home')
	else:
		form = EditProfileForm(instance= request.user)

	context = {'form': form}
	return render(request, 'registration/edit_profile.html', context)

authentication/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..forms import StudentInterestsForm, StudentSignUpForm, TakeQuizForm
from ..models import Quiz, Student, TakenQuiz, User, Profile
from .classroom import *
import uuid
from django.contrib import messages

def S_dashboard(request):
    return render(request, 'students/S_dashboard.html',{})
    
class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        request = self.request
        if request.method == 'POST':
            email = request.POST.get('email')
            try:
                if User.objects.filter(email = email).first():
                    messages.success(request, 'Email is taken.')
                    return redirect('signup')

                user = form.save()
                auth_token = str(uuid.uuid4())
                profile_obj = Profile.objects.create(user = user , auth_token = auth_token)
                profile_obj.save()
                send_mail_after_registration(email , auth_token)
                return redirect('/token')

            except Exception as e:
                print(e)


        return render(request , 'registration/signup_form.html')


@method_decorator(login_required, name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'students/interests_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(category__in=student_interests) \
            .exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator(login_required, name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__category') \
            .order_by('quiz__name')
        return queryset


@login_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'students/taken_quiz.html')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(quiz).exists():
                    return redirect('students:take_quiz', pk)
                else:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    score = round((correct_answers / total_questions) * 100.0, 2)
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=score)
                    if score < 60.0:
                        messages.warning(request, 'Better luck next time! Your score for the quiz %s was %s.' % (quiz.name, score))
                    else:
                        messages.success(request, 'Congratulations! You completed the quiz %s with success! You scored %s points.' % (quiz.name, score))
                    return redirect('students:quiz_list')
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'students/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'progress': progress
    })

authentication/templates/teachers/T_dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <h1 class="display-3 text-info text-center">Teacher</h1>
      <p class="text-center">A Student Quiz refers to a short test of knowledge, typically around 10 questions in length, with question formats often including multiple choice.</p>
      <p><a class="btn btn-primary btn-lg btn ml-5" href="{% url 'teachers:quiz_add_category' %}" role="button">Start &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock %}

authentication/templates/teachers/add_category.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <h1 class="display-3 text-info text-center">Add Category (Course/Subject)</h1>
      <p class="text-center">Add Category Name (Course/Subject) were in you can add an specific question to create.</p>
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
      <br>
      <p><a class="btn btn-primary btn-lg btn btn-block" href="{% url 'teachers:quiz_change_list' %}" role="button">Start Add Questions &raquo;</a></p>
      <p class="text-success">Note: Teacher can start adding questions when He/She created a Category (Course/Subject)</p> 
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
        </ol>
      </nav>
      <h2 class="mb-3">Add a new question</h2>
      <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-success">Save</button>
        <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
        </ol>
      </nav>
      <h2 class="mb-3">{{ question.txt }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        {{ formset.management_form }}
        {{ form|crispy }}
        <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
          <div class="card-header text-success bg-dark">
            <div class="row">
              <div class="col-8">
                <strong>Answers</strong>
              </div>
              <div class="col-2">
                <strong>Correct?</strong>
              </div>
              <div class="col-2">
                <strong>Delete?</strong>
              </div>
            </div>
          </div>
          {% for error in formset.non_form_errors %}
            <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
          {% endfor %}
          <div class="list-group list-group-flush list-group-formset">
            {% for form in formset %}
              <div class="list-group-item">
                <div class="row align-items-start">
                  <div class="col-8">
                    {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                    {{ form.text|as_crispy_field }}
                    {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
                  </div>
                  <div class="col-2">
                    <br>
                    {{ form.is_correct }}
                  </div>
                  <div class="col-2">
                    <br>
                    {% if form.instance.pk %}
                      {{ form.DELETE }}
                    {% endif %}
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <p>
          <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>20</strong> answers. Select at least one correct answer.</small>
        </p>
        <button type="submit" class="btn btn-outline-success">Save changes</button>
        <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-primary" role="button">Nevermind</a>
        <a href="{% url 'teachers:question_delete' quiz.pk question.pk %}" class="btn btn-outline-danger float-right">Delete</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
        </ol>
      </nav>
      <h2 class="mb-3">Confirm deletion</h2>
      <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
        <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/quiz_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item active" aria-current="page">Add a new quiz</li>
        </ol>
      </nav>
      <h2 class="mb-3">Add a new quiz</h2>
      <div class="row">
        <div class="col-md-6 col-sm-8 col-12">
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-success">Save</button>
            <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-info" role="button">Nevermind</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/quiz_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
        </ol>
      </nav>
      <h2 class="mb-3">
        {{ quiz.name }}
        <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-outline-primary float-right">View results</a>
      </h2>
      <div class="row mb-3">
        <div class="col-md-6 col-sm-8 col-12">
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-success">Save changes</button>
            <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-primary" role="button">Nevermind</a>
            <a href="{% url 'teachers:quiz_delete' quiz.pk %}" class="btn btn-outline-danger float-right">Delete</a>
          </form>
        </div>
      </div>
      <div class="card">
        <div class="card-header text-success bg-dark">
          <div class="row">
            <div class="col-10">
              <strong>Questions</strong>
            </div>
            <div class="col-2">
              <strong>Answers</strong>
            </div>
          </div>
        </div>
        <div class="list-group list-group-flush list-group-formset">
          {% for question in questions %}
            <div class="list-group-item">
              <div class="row">
                <div class="col-10">
                  <a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
                </div>
                <div class="col-2">
                  {{ question.answers_count }}
                </div>
              </div>
            </div>
          {% empty %}
            <div class="list-group-item text-center">
              <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'teachers:question_add' quiz.pk %}">add the first question</a>.</p>
            </div>
          {% endfor %}
        </div>
        <div class="card-footer">
          <a href="{% url 'teachers:question_add' quiz.pk %}" class=" btn btn-outline-primary btn-sm">Add question</a>
        </div>
      </div>
    </div>
  </div>
</div> 
{% endblock %}

authentication/templates/teachers/quiz_change_list.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"> {{ user.username }} Quizzes</li>
        </ol>
      </nav>
      <h2 class="mb-3">{{ user.username }} Quizzes</h2>
      <a href="{% url 'teachers:quiz_add' %}" class="btn btn-primary mb-3" role="button">Add quiz</a>
      <div class="card">
        <table class="table mb-0 text-success bg-dark ">
          <thead>
            <tr>
              <th>Quiz</th>
              <th>Category</th>
              <th>Questions</th>
              <th>Taken</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for quiz in quizzes %}
              <tr>
                <td class="align-middle"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
                <td class="align-middle">{{ quiz.category }}</td>
                <td class="align-middle">{{ quiz.questions_count }}</td>
                <td class="align-middle">{{ quiz.taken_count }}</td>
                <td class="text-right">
                  <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary">View results</a>
                </td>
              </tr>
            {% empty %}
              <tr>
                <td class="bg-light text-center font-italic" colspan="5">You haven't created any quiz yet.</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/quiz_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
        </ol>
      </nav>
      <h2 class="mb-3">Confirm deletion</h2>
      <p class="lead">Are you sure you want to delete the quiz <strong>"{{ quiz.name }}"</strong>? There is no going back.</p>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-success btn-lg">Yes, I'm sure</button>
        <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-info btn-lg" role="button">Nevermind</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

authentication/templates/teachers/quiz_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="card-body text-light bg-dark">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">{{ user.username }} Quizzes</a></li>
          <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">Results</li>
        </ol>
      </nav>
      <h2 class="mb-3">{{ quiz.name }} Results</h2>

      <div class="card">
        <div class="card-header">
          <strong>Taken Quizzes</strong>
          <span class="badge badge-pill badge-primary float-right">Average Score: {{ quiz_score.average_score|default_if_none:0.0 }}</span>
        </div>
        <table class="table mb-0 text-success bg-dark">
          <thead>
            <tr>
              <th>Student</th>
              <th>Date</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            {% for taken_quiz in taken_quizzes %}
              <tr>
                <td>{{ taken_quiz.student.user.username }}</td>
                <td>{{ taken_quiz.date|naturaltime }}</td>
                <td>{{ taken_quiz.score }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="card-footer text-muted">
          Total respondents: <strong>{{ total_taken_quizzes }}</strong>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}